create database crud;
use crud;
create table workers (
	id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	first_name VARCHAR(50),
	last_name VARCHAR(50),
	email VARCHAR(50),
	gender VARCHAR(50),
	country VARCHAR(50),
	job_title VARCHAR(50)
);
insert into workers (first_name, last_name, email, gender, country, job_title) values ('Goraud', 'Ysson', 'gysson0@ebay.co.uk', 'Male', 'Russia', 'Structural Analysis Engineer');
insert into workers (first_name, last_name, email, gender, country, job_title) values ('Shurlocke', 'Humerstone', 'shumerstone1@bizjournals.com', 'Male', 'Indonesia', 'Executive Secretary');
insert into workers (first_name, last_name, email, gender, country, job_title) values ('Stan', 'Wildin', 'swildin2@columbia.edu', 'Bigender', 'Nicaragua', 'Executive Secretary');
insert into workers (first_name, last_name, email, gender, country, job_title) values ('Rayna', 'Crispe', 'rcrispe3@fastcompany.com', 'Female', 'Argentina', 'Product Engineer');
insert into workers (first_name, last_name, email, gender, country, job_title) values ('Nance', 'Conway', 'nconway4@about.com', 'Bigender', 'France', 'Sales Representative');
insert into workers (first_name, last_name, email, gender, country, job_title) values ('Flore', 'Laste', 'flaste5@theglobeandmail.com', 'Agender', 'Albania', 'Clinical Specialist');
insert into workers (first_name, last_name, email, gender, country, job_title) values ('Benedicto', 'Northfield', 'bnorthfield6@who.int', 'Male', 'Indonesia', 'Help Desk Operator');
insert into workers (first_name, last_name, email, gender, country, job_title) values ('Jan', 'Chave', 'jchave7@mysql.com', 'Male', 'Poland', 'Paralegal');
insert into workers (first_name, last_name, email, gender, country, job_title) values ('Betty', 'Merryweather', 'bmerryweather8@columbia.edu', 'Female', 'Iran', 'Clinical Specialist');
insert into workers (first_name, last_name, email, gender, country, job_title) values ('Ray', 'Jessope', 'rjessope9@tripadvisor.com', 'Male', 'Philippines', 'Financial Advisor');
insert into workers (first_name, last_name, email, gender, country, job_title) values ('Deloria', 'Cason', 'dcasona@techcrunch.com', 'Female', 'Indonesia', 'Account Executive');
insert into workers (first_name, last_name, email, gender, country, job_title) values ('Monro', 'MacScherie', 'mmacscherieb@bizjournals.com', 'Male', 'Sweden', 'Product Engineer');
insert into workers (first_name, last_name, email, gender, country, job_title) values ('Hamil', 'Willmont', 'hwillmontc@elpais.com', 'Male', 'China', 'Health Coach IV');
insert into workers (first_name, last_name, email, gender, country, job_title) values ('Yolane', 'Hackinge', 'yhackinged@tuttocitta.it', 'Agender', 'Bhutan', 'General Manager');
insert into workers (first_name, last_name, email, gender, country, job_title) values ('Judon', 'Axel', 'jaxele@ifeng.com', 'Male', 'Bosnia and Herzegovina', 'Software Consultant');
insert into workers (first_name, last_name, email, gender, country, job_title) values ('Palm', 'Ghiron', 'pghironf@abc.net.au', 'Male', 'Brazil', 'Assistant Manager');
insert into workers (first_name, last_name, email, gender, country, job_title) values ('Dewie', 'Spurett', 'dspurettg@fotki.com', 'Genderfluid', 'China', 'Engineer IV');
insert into workers (first_name, last_name, email, gender, country, job_title) values ('Randolf', 'Buddell', 'rbuddellh@dailymail.co.uk', 'Male', 'China', 'Structural Analysis Engineer');
insert into workers (first_name, last_name, email, gender, country, job_title) values ('Fancy', 'Koopman', 'fkoopmani@house.gov', 'Female', 'Russia', 'Structural Engineer');
insert into workers (first_name, last_name, email, gender, country, job_title) values ('Eddie', 'Lundbech', 'elundbechj@yolasite.com', 'Female', 'Comoros', 'Data Coordiator');
insert into workers (first_name, last_name, email, gender, country, job_title) values ('Annemarie', 'World', 'aworldk@ustream.tv', 'Female', 'Philippines', 'Structural Analysis Engineer');
insert into workers (first_name, last_name, email, gender, country, job_title) values ('Ashlee', 'Medland', 'amedlandl@oracle.com', 'Female', 'China', 'Executive Secretary');
insert into workers (first_name, last_name, email, gender, country, job_title) values ('Moselle', 'Vasyaev', 'mvasyaevm@usatoday.com', 'Female', 'Brazil', 'Graphic Designer');
insert into workers (first_name, last_name, email, gender, country, job_title) values ('Retha', 'Ghidelli', 'rghidellin@npr.org', 'Female', 'United States', 'Senior Quality Engineer');
insert into workers (first_name, last_name, email, gender, country, job_title) values ('Nial', 'Dobie', 'ndobieo@skype.com', 'Male', 'China', 'Software Engineer III');
insert into workers (first_name, last_name, email, gender, country, job_title) values ('Buckie', 'Paireman', 'bpairemanp@shop-pro.jp', 'Male', 'Poland', 'Design Engineer');
insert into workers (first_name, last_name, email, gender, country, job_title) values ('Blythe', 'Carrier', 'bcarrierq@army.mil', 'Female', 'Mongolia', 'Paralegal');
insert into workers (first_name, last_name, email, gender, country, job_title) values ('Kip', 'Cheverton', 'kchevertonr@merriam-webster.com', 'Female', 'Philippines', 'Geologist IV');
insert into workers (first_name, last_name, email, gender, country, job_title) values ('Sheelagh', 'Urch', 'surchs@rediff.com', 'Genderqueer', 'China', 'Sales Associate');
insert into workers (first_name, last_name, email, gender, country, job_title) values ('Cecelia', 'Yanshonok', 'cyanshonokt@dion.ne.jp', 'Female', 'Cyprus', 'Structural Analysis Engineer');
insert into workers (first_name, last_name, email, gender, country, job_title) values ('Alan', 'Cestard', 'acestardu@mac.com', 'Male', 'Russia', 'Data Coordiator');
insert into workers (first_name, last_name, email, gender, country, job_title) values ('Winonah', 'Ryhorovich', 'wryhorovichv@qq.com', 'Female', 'Russia', 'Computer Systems Analyst IV');
insert into workers (first_name, last_name, email, gender, country, job_title) values ('Fax', 'Dohr', 'fdohrw@dedecms.com', 'Male', 'Brazil', 'Cost Accountant');
insert into workers (first_name, last_name, email, gender, country, job_title) values ('Baily', 'Jerred', 'bjerredx@github.io', 'Male', 'Brazil', 'Marketing Assistant');
insert into workers (first_name, last_name, email, gender, country, job_title) values ('Linus', 'Gibberd', 'lgibberdy@etsy.com', 'Male', 'Indonesia', 'VP Accounting');
insert into workers (first_name, last_name, email, gender, country, job_title) values ('Joyann', 'Wogdon', 'jwogdonz@wufoo.com', 'Female', 'Japan', 'Senior Developer');
insert into workers (first_name, last_name, email, gender, country, job_title) values ('Berthe', 'Ades', 'bades10@xinhuanet.com', 'Female', 'Vietnam', 'Information Systems Manager');
insert into workers (first_name, last_name, email, gender, country, job_title) values ('Aidan', 'Fairhall', 'afairhall11@nature.com', 'Female', 'Thailand', 'Developer II');
insert into workers (first_name, last_name, email, gender, country, job_title) values ('Aloise', 'Tanswill', 'atanswill12@japanpost.jp', 'Female', 'Serbia', 'Environmental Specialist');
insert into workers (first_name, last_name, email, gender, country, job_title) values ('Dacia', 'Ghion', 'dghion13@statcounter.com', 'Female', 'Yemen', 'Analyst Programmer');
insert into workers (first_name, last_name, email, gender, country, job_title) values ('Stephannie', 'Broxup', 'sbroxup14@marketwatch.com', 'Female', 'Macedonia', 'Account Coordinator');
insert into workers (first_name, last_name, email, gender, country, job_title) values ('Phaedra', 'Okenden', 'pokenden15@google.fr', 'Female', 'Argentina', 'Analog Circuit Design manager');
insert into workers (first_name, last_name, email, gender, country, job_title) values ('Sig', 'Puttnam', 'sputtnam16@i2i.jp', 'Male', 'China', 'Office Assistant I');
insert into workers (first_name, last_name, email, gender, country, job_title) values ('Michael', 'Dolling', 'mdolling17@simplemachines.org', 'Male', 'Indonesia', 'Occupational Therapist');
insert into workers (first_name, last_name, email, gender, country, job_title) values ('Bax', 'Goggan', 'bgoggan18@a8.net', 'Male', 'Sweden', 'Biostatistician III');
insert into workers (first_name, last_name, email, gender, country, job_title) values ('Delmar', 'Bynold', 'dbynold19@chron.com', 'Male', 'Armenia', 'Senior Developer');
insert into workers (first_name, last_name, email, gender, country, job_title) values ('Alexine', 'Borghese', 'aborghese1a@columbia.edu', 'Female', 'New Zealand', 'Actuary');
insert into workers (first_name, last_name, email, gender, country, job_title) values ('Fransisco', 'Walasik', 'fwalasik1b@java.com', 'Male', 'Argentina', 'Nurse');
insert into workers (first_name, last_name, email, gender, country, job_title) values ('Giustina', 'Kearns', 'gkearns1c@princeton.edu', 'Female', 'Peru', 'Staff Accountant III');
insert into workers (first_name, last_name, email, gender, country, job_title) values ('Katha', 'Hayter', 'khayter1d@aboutads.info', 'Female', 'China', 'Safety Technician I');
insert into workers (first_name, last_name, email, gender, country, job_title) values ('Glendon', 'Kinsella', 'gkinsella1e@4shared.com', 'Male', 'Afghanistan', 'Programmer III');
insert into workers (first_name, last_name, email, gender, country, job_title) values ('Patrick', 'Summerell', 'psummerell1f@facebook.com', 'Male', 'Brazil', 'Financial Advisor');
insert into workers (first_name, last_name, email, gender, country, job_title) values ('Joaquin', 'Breton', 'jbreton1g@is.gd', 'Male', 'China', 'Design Engineer');
insert into workers (first_name, last_name, email, gender, country, job_title) values ('Reginauld', 'Cockman', 'rcockman1h@ucla.edu', 'Male', 'Indonesia', 'Technical Writer');
insert into workers (first_name, last_name, email, gender, country, job_title) values ('Humphrey', 'Gilardoni', 'hgilardoni1i@uol.com.br', 'Male', 'Japan', 'Account Executive');
insert into workers (first_name, last_name, email, gender, country, job_title) values ('Bondon', 'Simionato', 'bsimionato1j@joomla.org', 'Male', 'Portugal', 'Computer Systems Analyst II');
insert into workers (first_name, last_name, email, gender, country, job_title) values ('Kipper', 'O''Spillane', 'kospillane1k@lulu.com', 'Male', 'Indonesia', 'Project Manager');
insert into workers (first_name, last_name, email, gender, country, job_title) values ('Ethelbert', 'Scholard', 'escholard1l@webmd.com', 'Bigender', 'France', 'Graphic Designer');
insert into workers (first_name, last_name, email, gender, country, job_title) values ('Kev', 'Hanbury-Brown', 'khanburybrown1m@goo.gl', 'Genderfluid', 'China', 'Database Administrator II');
insert into workers (first_name, last_name, email, gender, country, job_title) values ('Sky', 'Elegood', 'selegood1n@seattletimes.com', 'Male', 'China', 'Nuclear Power Engineer');
insert into workers (first_name, last_name, email, gender, country, job_title) values ('Tyrus', 'Yanyushkin', 'tyanyushkin1o@taobao.com', 'Male', 'China', 'Legal Assistant');
insert into workers (first_name, last_name, email, gender, country, job_title) values ('Kori', 'Lebourn', 'klebourn1p@goo.gl', 'Female', 'Peru', 'Engineer II');
insert into workers (first_name, last_name, email, gender, country, job_title) values ('Cairistiona', 'Antham', 'cantham1q@linkedin.com', 'Female', 'Russia', 'Account Executive');
insert into workers (first_name, last_name, email, gender, country, job_title) values ('Earvin', 'Valiant', 'evaliant1r@networksolutions.com', 'Male', 'China', 'Actuary');
insert into workers (first_name, last_name, email, gender, country, job_title) values ('Jacynth', 'Heister', 'jheister1s@seattletimes.com', 'Female', 'China', 'Registered Nurse');
insert into workers (first_name, last_name, email, gender, country, job_title) values ('Elvina', 'Fashion', 'efashion1t@youtube.com', 'Female', 'Argentina', 'Internal Auditor');
insert into workers (first_name, last_name, email, gender, country, job_title) values ('Faythe', 'Wheelhouse', 'fwheelhouse1u@sourceforge.net', 'Female', 'Nepal', 'Administrative Officer');
insert into workers (first_name, last_name, email, gender, country, job_title) values ('Nissie', 'Gaskamp', 'ngaskamp1v@google.com.au', 'Female', 'Philippines', 'Senior Editor');
insert into workers (first_name, last_name, email, gender, country, job_title) values ('Kaylyn', 'McOrkil', 'kmcorkil1w@apple.com', 'Female', 'Brazil', 'Financial Analyst');
insert into workers (first_name, last_name, email, gender, country, job_title) values ('Amber', 'Reiling', 'areiling1x@un.org', 'Female', 'China', 'Programmer Analyst II');
insert into workers (first_name, last_name, email, gender, country, job_title) values ('Mariele', 'Biasio', 'mbiasio1y@ucla.edu', 'Female', 'Russia', 'Product Engineer');
insert into workers (first_name, last_name, email, gender, country, job_title) values ('Gates', 'Salaman', 'gsalaman1z@who.int', 'Female', 'China', 'Web Developer III');
insert into workers (first_name, last_name, email, gender, country, job_title) values ('Andeee', 'Stefi', 'astefi20@homestead.com', 'Female', 'Peru', 'Statistician III');
insert into workers (first_name, last_name, email, gender, country, job_title) values ('Donni', 'Eusden', 'deusden21@tuttocitta.it', 'Female', 'China', 'Structural Engineer');
insert into workers (first_name, last_name, email, gender, country, job_title) values ('Jaime', 'Berthelmot', 'jberthelmot22@pbs.org', 'Female', 'Brazil', 'VP Marketing');
insert into workers (first_name, last_name, email, gender, country, job_title) values ('Tannie', 'Davidofski', 'tdavidofski23@jalbum.net', 'Male', 'Czech Republic', 'Senior Cost Accountant');
insert into workers (first_name, last_name, email, gender, country, job_title) values ('Carrissa', 'Debrick', 'cdebrick24@dailymotion.com', 'Female', 'Indonesia', 'Librarian');
insert into workers (first_name, last_name, email, gender, country, job_title) values ('Shayla', 'Yateman', 'syateman25@un.org', 'Female', 'France', 'Technical Writer');
insert into workers (first_name, last_name, email, gender, country, job_title) values ('Louis', 'Jirzik', 'ljirzik26@java.com', 'Male', 'China', 'Web Developer I');
insert into workers (first_name, last_name, email, gender, country, job_title) values ('Hartwell', 'Belhome', 'hbelhome27@artisteer.com', 'Male', 'China', 'Accountant IV');
insert into workers (first_name, last_name, email, gender, country, job_title) values ('Gretal', 'Kneebone', 'gkneebone28@craigslist.org', 'Female', 'Indonesia', 'Software Consultant');
insert into workers (first_name, last_name, email, gender, country, job_title) values ('Domingo', 'McDermid', 'dmcdermid29@nature.com', 'Male', 'China', 'VP Product Management');
insert into workers (first_name, last_name, email, gender, country, job_title) values ('Lucia', 'Nunes Nabarro', 'lnunesnabarro2a@com.com', 'Female', 'United Kingdom', 'Geological Engineer');
insert into workers (first_name, last_name, email, gender, country, job_title) values ('Clarissa', 'Olenikov', 'colenikov2b@lulu.com', 'Bigender', 'Poland', 'Pharmacist');
insert into workers (first_name, last_name, email, gender, country, job_title) values ('Hester', 'Whitta', 'hwhitta2c@yale.edu', 'Female', 'Indonesia', 'Compensation Analyst');
insert into workers (first_name, last_name, email, gender, country, job_title) values ('Domingo', 'Paddell', 'dpaddell2d@nih.gov', 'Male', 'South Africa', 'Associate Professor');
insert into workers (first_name, last_name, email, gender, country, job_title) values ('Felipa', 'Johansen', 'fjohansen2e@addtoany.com', 'Female', 'China', 'Senior Cost Accountant');
insert into workers (first_name, last_name, email, gender, country, job_title) values ('Selma', 'Rivalant', 'srivalant2f@hostgator.com', 'Female', 'Norway', 'Software Engineer II');
insert into workers (first_name, last_name, email, gender, country, job_title) values ('Renate', 'Burgum', 'rburgum2g@alibaba.com', 'Female', 'Tunisia', 'Statistician III');
insert into workers (first_name, last_name, email, gender, country, job_title) values ('August', 'Vanns', 'avanns2h@cdc.gov', 'Male', 'Philippines', 'Business Systems Development Analyst');
insert into workers (first_name, last_name, email, gender, country, job_title) values ('Tova', 'Mylan', 'tmylan2i@constantcontact.com', 'Female', 'Finland', 'Software Test Engineer II');
insert into workers (first_name, last_name, email, gender, country, job_title) values ('Janean', 'Clougher', 'jclougher2j@mlb.com', 'Female', 'China', 'Office Assistant III');
insert into workers (first_name, last_name, email, gender, country, job_title) values ('Neils', 'Normanvill', 'nnormanvill2k@bing.com', 'Male', 'Russia', 'Community Outreach Specialist');
insert into workers (first_name, last_name, email, gender, country, job_title) values ('Lavena', 'Heustace', 'lheustace2l@princeton.edu', 'Female', 'Sweden', 'Assistant Manager');
insert into workers (first_name, last_name, email, gender, country, job_title) values ('Hans', 'Pressdee', 'hpressdee2m@springer.com', 'Male', 'Indonesia', 'Sales Associate');
insert into workers (first_name, last_name, email, gender, country, job_title) values ('Astra', 'Bagshaw', 'abagshaw2n@php.net', 'Female', 'Indonesia', 'Environmental Tech');
insert into workers (first_name, last_name, email, gender, country, job_title) values ('Josepha', 'Josh', 'jjosh2o@fc2.com', 'Bigender', 'Russia', 'Recruiting Manager');
insert into workers (first_name, last_name, email, gender, country, job_title) values ('Tally', 'Umney', 'tumney2p@sourceforge.net', 'Female', 'United States', 'Sales Representative');
insert into workers (first_name, last_name, email, gender, country, job_title) values ('Willis', 'Petters', 'wpetters2q@harvard.edu', 'Male', 'China', 'Quality Control Specialist');
insert into workers (first_name, last_name, email, gender, country, job_title) values ('Krispin', 'Haughin', 'khaughin2r@1und1.de', 'Male', 'Indonesia', 'Pharmacist');
insert into workers (first_name, last_name, email, gender, country, job_title) values ('Joanna', 'Bessett', 'jbessett2s@phoca.cz', 'Female', 'Macedonia', 'Computer Systems Analyst II');
insert into workers (first_name, last_name, email, gender, country, job_title) values ('Dulcie', 'Cridge', 'dcridge2t@oaic.gov.au', 'Female', 'Kuwait', 'Cost Accountant');
insert into workers (first_name, last_name, email, gender, country, job_title) values ('Maryrose', 'Caltera', 'mcaltera2u@blogs.com', 'Female', 'Russia', 'Budget/Accounting Analyst I');
insert into workers (first_name, last_name, email, gender, country, job_title) values ('Gilberta', 'Trott', 'gtrott2v@devhub.com', 'Bigender', 'Philippines', 'Food Chemist');
insert into workers (first_name, last_name, email, gender, country, job_title) values ('Arleta', 'Bateup', 'abateup2w@ask.com', 'Genderfluid', 'South Africa', 'Recruiting Manager');
insert into workers (first_name, last_name, email, gender, country, job_title) values ('Ax', 'Bisseker', 'abisseker2x@canalblog.com', 'Male', 'China', 'VP Product Management');
insert into workers (first_name, last_name, email, gender, country, job_title) values ('Bernardo', 'Wildish', 'bwildish2y@seattletimes.com', 'Male', 'Brazil', 'Nurse Practicioner');
insert into workers (first_name, last_name, email, gender, country, job_title) values ('Tanny', 'McBean', 'tmcbean2z@bloomberg.com', 'Male', 'Greece', 'VP Sales');
insert into workers (first_name, last_name, email, gender, country, job_title) values ('Carlie', 'Mc Comb', 'cmccomb30@craigslist.org', 'Genderqueer', 'Sweden', 'Chemical Engineer');
insert into workers (first_name, last_name, email, gender, country, job_title) values ('Lief', 'Andor', 'landor31@github.com', 'Male', 'Russia', 'Recruiter');
insert into workers (first_name, last_name, email, gender, country, job_title) values ('Costanza', 'Stimson', 'cstimson32@i2i.jp', 'Female', 'Philippines', 'Structural Engineer');
insert into workers (first_name, last_name, email, gender, country, job_title) values ('Willy', 'Tabourel', 'wtabourel33@yolasite.com', 'Male', 'Indonesia', 'Desktop Support Technician');
insert into workers (first_name, last_name, email, gender, country, job_title) values ('Sanderson', 'Utterson', 'sutterson34@i2i.jp', 'Male', 'Moldova', 'Human Resources Assistant I');
insert into workers (first_name, last_name, email, gender, country, job_title) values ('Martynne', 'Defau', 'mdefau35@cnet.com', 'Female', 'China', 'Cost Accountant');
insert into workers (first_name, last_name, email, gender, country, job_title) values ('Armand', 'Pallister', 'apallister36@xing.com', 'Male', 'Greece', 'Speech Pathologist');
insert into workers (first_name, last_name, email, gender, country, job_title) values ('Miller', 'Ardling', 'mardling37@forbes.com', 'Male', 'Indonesia', 'Tax Accountant');
insert into workers (first_name, last_name, email, gender, country, job_title) values ('Florian', 'Evemy', 'fevemy38@webmd.com', 'Male', 'Pakistan', 'Administrative Assistant I');
insert into workers (first_name, last_name, email, gender, country, job_title) values ('Horten', 'Pressdee', 'hpressdee39@lulu.com', 'Male', 'South Africa', 'Clinical Specialist');
insert into workers (first_name, last_name, email, gender, country, job_title) values ('Lucias', 'Waggett', 'lwaggett3a@parallels.com', 'Male', 'France', 'Community Outreach Specialist');
insert into workers (first_name, last_name, email, gender, country, job_title) values ('Craggy', 'Arnefield', 'carnefield3b@apache.org', 'Male', 'Russia', 'Data Coordiator');
insert into workers (first_name, last_name, email, gender, country, job_title) values ('Naomi', 'Clemence', 'nclemence3c@narod.ru', 'Female', 'Portugal', 'Research Nurse');
insert into workers (first_name, last_name, email, gender, country, job_title) values ('Anne', 'Swinyard', 'aswinyard3d@storify.com', 'Female', 'Finland', 'Computer Systems Analyst III');
insert into workers (first_name, last_name, email, gender, country, job_title) values ('Myriam', 'Smelley', 'msmelley3e@yellowbook.com', 'Female', 'Indonesia', 'Information Systems Manager');
insert into workers (first_name, last_name, email, gender, country, job_title) values ('Frank', 'Crut', 'fcrut3f@mapquest.com', 'Female', 'China', 'Food Chemist');
insert into workers (first_name, last_name, email, gender, country, job_title) values ('Wilmette', 'O Sullivan', 'wosullivan3g@plala.or.jp', 'Bigender', 'Poland', 'Payment Adjustment Coordinator');
insert into workers (first_name, last_name, email, gender, country, job_title) values ('Francklin', 'Starbeck', 'fstarbeck3h@quantcast.com', 'Male', 'Saudi Arabia', 'Office Assistant III');
insert into workers (first_name, last_name, email, gender, country, job_title) values ('Decca', 'Langhor', 'dlanghor3i@bizjournals.com', 'Male', 'Philippines', 'VP Accounting');
insert into workers (first_name, last_name, email, gender, country, job_title) values ('Karil', 'Gear', 'kgear3j@oakley.com', 'Female', 'China', 'Cost Accountant');
insert into workers (first_name, last_name, email, gender, country, job_title) values ('Kamilah', 'Agronski', 'kagronski3k@hao123.com', 'Female', 'China', 'Executive Secretary');
insert into workers (first_name, last_name, email, gender, country, job_title) values ('Ignace', 'Winscom', 'iwinscom3l@soundcloud.com', 'Male', 'China', 'VP Accounting');
insert into workers (first_name, last_name, email, gender, country, job_title) values ('Sheffield', 'Giacaponi', 'sgiacaponi3m@harvard.edu', 'Male', 'Nigeria', 'Software Test Engineer IV');
insert into workers (first_name, last_name, email, gender, country, job_title) values ('Rafael', 'Snaddon', 'rsnaddon3n@mediafire.com', 'Male', 'Croatia', 'Assistant Professor');
insert into workers (first_name, last_name, email, gender, country, job_title) values ('Chlo', 'Cornbill', 'ccornbill3o@mysql.com', 'Female', 'Indonesia', 'Pharmacist');
insert into workers (first_name, last_name, email, gender, country, job_title) values ('Evania', 'Readshall', 'ereadshall3p@sciencedaily.com', 'Female', 'China', 'VP Sales');
insert into workers (first_name, last_name, email, gender, country, job_title) values ('Tate', 'Struijs', 'tstruijs3q@weather.com', 'Female', 'Brazil', 'Teacher');
insert into workers (first_name, last_name, email, gender, country, job_title) values ('Janela', 'Mechan', 'jmechan3r@opera.com', 'Female', 'Philippines', 'Geological Engineer');
insert into workers (first_name, last_name, email, gender, country, job_title) values ('Emmit', 'Dalgety', 'edalgety3s@feedburner.com', 'Male', 'Ethiopia', 'Assistant Manager');
insert into workers (first_name, last_name, email, gender, country, job_title) values ('Brianna', 'M''Quhan', 'bmquhan3t@dailymotion.com', 'Female', 'Brazil', 'Actuary');
insert into workers (first_name, last_name, email, gender, country, job_title) values ('Zacharia', 'Cuschieri', 'zcuschieri3u@marketwatch.com', 'Male', 'Indonesia', 'Senior Editor');
insert into workers (first_name, last_name, email, gender, country, job_title) values ('Marlowe', 'Sackett', 'msackett3v@live.com', 'Male', 'Ukraine', 'Assistant Media Planner');
insert into workers (first_name, last_name, email, gender, country, job_title) values ('Shermy', 'Guiel', 'sguiel3w@amazon.de', 'Male', 'Brazil', 'Tax Accountant');
insert into workers (first_name, last_name, email, gender, country, job_title) values ('Trever', 'De Vaar', 'tdevaar3x@google.co.jp', 'Male', 'Norway', 'Statistician III');
insert into workers (first_name, last_name, email, gender, country, job_title) values ('Del', 'Francino', 'dfrancino3y@marriott.com', 'Female', 'China', 'Media Manager I');
insert into workers (first_name, last_name, email, gender, country, job_title) values ('Odessa', 'Dedam', 'odedam3z@odnoklassniki.ru', 'Female', 'Peru', 'Analyst Programmer');
insert into workers (first_name, last_name, email, gender, country, job_title) values ('Ariella', 'Storch', 'astorch40@columbia.edu', 'Female', 'Russia', 'Compensation Analyst');
insert into workers (first_name, last_name, email, gender, country, job_title) values ('Gwenni', 'Francklyn', 'gfrancklyn41@slideshare.net', 'Female', 'Macedonia', 'Registered Nurse');
insert into workers (first_name, last_name, email, gender, country, job_title) values ('Donnie', 'Ovey', 'dovey42@wufoo.com', 'Non-binary', 'Thailand', 'Software Engineer III');
insert into workers (first_name, last_name, email, gender, country, job_title) values ('Duffie', 'Rainger', 'drainger43@discuz.net', 'Male', 'Philippines', 'Safety Technician IV');
insert into workers (first_name, last_name, email, gender, country, job_title) values ('Arabela', 'Chattaway', 'achattaway44@nba.com', 'Female', 'China', 'Research Associate');
insert into workers (first_name, last_name, email, gender, country, job_title) values ('Berny', 'Epton', 'bepton45@so-net.ne.jp', 'Male', 'Honduras', 'Chief Design Engineer');
insert into workers (first_name, last_name, email, gender, country, job_title) values ('Lelia', 'Paybody', 'lpaybody46@sogou.com', 'Female', 'Dominican Republic', 'Cost Accountant');
insert into workers (first_name, last_name, email, gender, country, job_title) values ('Karyl', 'Birdfield', 'kbirdfield47@mapy.cz', 'Female', 'China', 'Technical Writer');
insert into workers (first_name, last_name, email, gender, country, job_title) values ('Philip', 'Sand', 'psand48@bizjournals.com', 'Genderqueer', 'Indonesia', 'Database Administrator III');
insert into workers (first_name, last_name, email, gender, country, job_title) values ('Ty', 'Dorkins', 'tdorkins49@cpanel.net', 'Polygender', 'Indonesia', 'Quality Engineer');
insert into workers (first_name, last_name, email, gender, country, job_title) values ('Donnie', 'Beale', 'dbeale4a@icio.us', 'Male', 'Indonesia', 'Analog Circuit Design manager');
insert into workers (first_name, last_name, email, gender, country, job_title) values ('Padgett', 'Ivanchin', 'pivanchin4b@theglobeandmail.com', 'Male', 'Gabon', 'VP Sales');
insert into workers (first_name, last_name, email, gender, country, job_title) values ('Curran', 'Tuttiett', 'ctuttiett4c@theglobeandmail.com', 'Male', 'Philippines', 'Software Engineer I');
insert into workers (first_name, last_name, email, gender, country, job_title) values ('Wayne', 'Gregoretti', 'wgregoretti4d@deviantart.com', 'Non-binary', 'Argentina', 'VP Marketing');
insert into workers (first_name, last_name, email, gender, country, job_title) values ('Aloise', 'Papaccio', 'apapaccio4e@microsoft.com', 'Female', 'Colombia', 'Nuclear Power Engineer');
insert into workers (first_name, last_name, email, gender, country, job_title) values ('Misha', 'Claypoole', 'mclaypoole4f@dailymail.co.uk', 'Female', 'Indonesia', 'Web Developer IV');
insert into workers (first_name, last_name, email, gender, country, job_title) values ('Dante', 'Matijasevic', 'dmatijasevic4g@army.mil', 'Male', 'United States', 'GIS Technical Architect');
insert into workers (first_name, last_name, email, gender, country, job_title) values ('Erica', 'Nafzger', 'enafzger4h@psu.edu', 'Female', 'Sweden', 'Human Resources Manager');
insert into workers (first_name, last_name, email, gender, country, job_title) values ('Verna', 'Gallichiccio', 'vgallichiccio4i@ihg.com', 'Female', 'Indonesia', 'Chief Design Engineer');
insert into workers (first_name, last_name, email, gender, country, job_title) values ('Cassondra', 'Bilyard', 'cbilyard4j@purevolume.com', 'Female', 'Albania', 'Assistant Media Planner');
insert into workers (first_name, last_name, email, gender, country, job_title) values ('Lorilyn', 'Marjanovic', 'lmarjanovic4k@patch.com', 'Female', 'United States', 'Nuclear Power Engineer');
insert into workers (first_name, last_name, email, gender, country, job_title) values ('Catherina', 'Gatherer', 'cgatherer4l@woothemes.com', 'Female', 'Russia', 'Recruiter');
insert into workers (first_name, last_name, email, gender, country, job_title) values ('Joleen', 'Macey', 'jmacey4m@utexas.edu', 'Female', 'China', 'Chief Design Engineer');
insert into workers (first_name, last_name, email, gender, country, job_title) values ('Perkin', 'Wisher', 'pwisher4n@goo.ne.jp', 'Male', 'Macedonia', 'GIS Technical Architect');
insert into workers (first_name, last_name, email, gender, country, job_title) values ('Thibaud', 'Barson', 'tbarson4o@macromedia.com', 'Male', 'China', 'Analog Circuit Design manager');
insert into workers (first_name, last_name, email, gender, country, job_title) values ('Betty', 'Mate', 'bmate4p@vimeo.com', 'Female', 'China', 'VP Quality Control');
insert into workers (first_name, last_name, email, gender, country, job_title) values ('Lita', 'Larchier', 'llarchier4q@homestead.com', 'Female', 'Ukraine', 'Analog Circuit Design manager');
insert into workers (first_name, last_name, email, gender, country, job_title) values ('Sax', 'Roddick', 'sroddick4r@apple.com', 'Male', 'Thailand', 'VP Sales');
insert into workers (first_name, last_name, email, gender, country, job_title) values ('Martha', 'Domelow', 'mdomelow4s@google.de', 'Genderqueer', 'Russia', 'Research Assistant I');
insert into workers (first_name, last_name, email, gender, country, job_title) values ('Moritz', 'Pochon', 'mpochon4t@jimdo.com', 'Genderfluid', 'Latvia', 'Desktop Support Technician');
insert into workers (first_name, last_name, email, gender, country, job_title) values ('Pyotr', 'Danelut', 'pdanelut4u@hostgator.com', 'Male', 'Philippines', 'Biostatistician IV');
insert into workers (first_name, last_name, email, gender, country, job_title) values ('Antoni', 'Skiggs', 'askiggs4v@histats.com', 'Bigender', 'Bolivia', 'VP Quality Control');
insert into workers (first_name, last_name, email, gender, country, job_title) values ('Giorgi', 'Kausche', 'gkausche4w@wikimedia.org', 'Male', 'Brazil', 'Web Designer IV');
insert into workers (first_name, last_name, email, gender, country, job_title) values ('Maude', 'Le Frank', 'mlefrank4x@purevolume.com', 'Female', 'Russia', 'Human Resources Manager');
insert into workers (first_name, last_name, email, gender, country, job_title) values ('Cristobal', 'Sherry', 'csherry4y@about.com', 'Male', 'China', 'Quality Engineer');
insert into workers (first_name, last_name, email, gender, country, job_title) values ('Roxanna', 'Elias', 'relias4z@reference.com', 'Female', 'Japan', 'Compensation Analyst');
insert into workers (first_name, last_name, email, gender, country, job_title) values ('Rory', 'Tarply', 'rtarply50@youtu.be', 'Male', 'China', 'Occupational Therapist');
insert into workers (first_name, last_name, email, gender, country, job_title) values ('Mahmoud', 'Henden', 'mhenden51@alibaba.com', 'Male', 'France', 'Assistant Professor');
insert into workers (first_name, last_name, email, gender, country, job_title) values ('Jeffy', 'Fearnyhough', 'jfearnyhough52@arizona.edu', 'Male', 'Indonesia', 'Staff Scientist');
insert into workers (first_name, last_name, email, gender, country, job_title) values ('Alix', 'D''Acth', 'adacth53@toplist.cz', 'Male', 'China', 'Senior Editor');
insert into workers (first_name, last_name, email, gender, country, job_title) values ('Barrie', 'Connue', 'bconnue54@cafepress.com', 'Male', 'Philippines', 'Software Engineer III');
insert into workers (first_name, last_name, email, gender, country, job_title) values ('Norbie', 'Sollitt', 'nsollitt55@discuz.net', 'Male', 'Czech Republic', 'Staff Accountant IV');
insert into workers (first_name, last_name, email, gender, country, job_title) values ('Logan', 'Stroder', 'lstroder56@1und1.de', 'Male', 'Ethiopia', 'Senior Financial Analyst');
insert into workers (first_name, last_name, email, gender, country, job_title) values ('Dona', 'Yonge', 'dyonge57@nationalgeographic.com', 'Female', 'Israel', 'Registered Nurse');
insert into workers (first_name, last_name, email, gender, country, job_title) values ('Theressa', 'Braim', 'tbraim58@i2i.jp', 'Female', 'Philippines', 'Office Assistant II');
insert into workers (first_name, last_name, email, gender, country, job_title) values ('Gaylor', 'Whitwood', 'gwhitwood59@devhub.com', 'Male', 'Czech Republic', 'Assistant Media Planner');
insert into workers (first_name, last_name, email, gender, country, job_title) values ('Xena', 'Handlin', 'xhandlin5a@facebook.com', 'Female', 'Peru', 'Quality Engineer');
insert into workers (first_name, last_name, email, gender, country, job_title) values ('Hillel', 'Pierse', 'hpierse5b@epa.gov', 'Male', 'Mongolia', 'Desktop Support Technician');
insert into workers (first_name, last_name, email, gender, country, job_title) values ('Thomasa', 'Kleinzweig', 'tkleinzweig5c@flickr.com', 'Female', 'Russia', 'Senior Sales Associate');
insert into workers (first_name, last_name, email, gender, country, job_title) values ('Kevyn', 'Radclyffe', 'kradclyffe5d@noaa.gov', 'Agender', 'Kenya', 'Associate Professor');
insert into workers (first_name, last_name, email, gender, country, job_title) values ('Any', 'Guerrin', 'aguerrin5e@php.net', 'Male', 'Brazil', 'Desktop Support Technician');
insert into workers (first_name, last_name, email, gender, country, job_title) values ('Kerry', 'Canape', 'kcanape5f@scientificamerican.com', 'Male', 'Indonesia', 'Chemical Engineer');
insert into workers (first_name, last_name, email, gender, country, job_title) values ('Salomone', 'Gilligan', 'sgilligan5g@reddit.com', 'Male', 'Tanzania', 'Budget/Accounting Analyst I');
insert into workers (first_name, last_name, email, gender, country, job_title) values ('Roberto', 'Hammerberger', 'rhammerberger5h@ifeng.com', 'Male', 'Morocco', 'Staff Scientist');
insert into workers (first_name, last_name, email, gender, country, job_title) values ('Alexander', 'Lavelle', 'alavelle5i@dion.ne.jp', 'Male', 'Greece', 'Financial Advisor');
insert into workers (first_name, last_name, email, gender, country, job_title) values ('Constantino', 'Jantzen', 'cjantzen5j@themeforest.net', 'Male', 'Guatemala', 'Software Test Engineer I');
insert into workers (first_name, last_name, email, gender, country, job_title) values ('Edith', 'Van Bruggen', 'evanbruggen5k@eepurl.com', 'Female', 'Brazil', 'Sales Representative');
insert into workers (first_name, last_name, email, gender, country, job_title) values ('Simon', 'Siemens', 'ssiemens5l@ed.gov', 'Male', 'France', 'Marketing Assistant');
insert into workers (first_name, last_name, email, gender, country, job_title) values ('Weider', 'Stillert', 'wstillert5m@delicious.com', 'Male', 'Macedonia', 'Marketing Assistant');
insert into workers (first_name, last_name, email, gender, country, job_title) values ('Janis', 'Abell', 'jabell5n@who.int', 'Bigender', 'China', 'Human Resources Assistant IV');
insert into workers (first_name, last_name, email, gender, country, job_title) values ('Chucho', 'Lemonby', 'clemonby5o@photobucket.com', 'Male', 'Georgia', 'Health Coach III');
insert into workers (first_name, last_name, email, gender, country, job_title) values ('Randi', 'Skuce', 'rskuce5p@examiner.com', 'Polygender', 'United States', 'Actuary');
insert into workers (first_name, last_name, email, gender, country, job_title) values ('Leona', 'Murdie', 'lmurdie5q@accuweather.com', 'Female', 'Sweden', 'Administrative Assistant I');
insert into workers (first_name, last_name, email, gender, country, job_title) values ('Jordain', 'Tredwell', 'jtredwell5r@mlb.com', 'Female', 'Philippines', 'Systems Administrator II');
insert into workers (first_name, last_name, email, gender, country, job_title) values ('Raymund', 'Yare', 'ryare5s@alibaba.com', 'Male', 'Brazil', 'Assistant Professor');
insert into workers (first_name, last_name, email, gender, country, job_title) values ('Honey', 'Bidewel', 'hbidewel5t@dropbox.com', 'Female', 'Brazil', 'Data Coordiator');
insert into workers (first_name, last_name, email, gender, country, job_title) values ('Caralie', 'Give', 'cgive5u@exblog.jp', 'Genderfluid', 'China', 'VP Marketing');
insert into workers (first_name, last_name, email, gender, country, job_title) values ('Shea', 'Beavan', 'sbeavan5v@google.com.au', 'Male', 'China', 'Registered Nurse');
insert into workers (first_name, last_name, email, gender, country, job_title) values ('George', 'Goff', 'ggoff5w@friendfeed.com', 'Male', 'China', 'Pharmacist');
insert into workers (first_name, last_name, email, gender, country, job_title) values ('Anatole', 'Bohler', 'abohler5x@naver.com', 'Male', 'China', 'Help Desk Technician');
insert into workers (first_name, last_name, email, gender, country, job_title) values ('Stanislas', 'Burras', 'sburras5y@networksolutions.com', 'Male', 'Russia', 'Developer I');
insert into workers (first_name, last_name, email, gender, country, job_title) values ('Sydelle', 'Bachura', 'sbachura5z@tumblr.com', 'Female', 'China', 'Staff Accountant I');
insert into workers (first_name, last_name, email, gender, country, job_title) values ('Prentiss', 'Hundal', 'phundal60@zimbio.com', 'Non-binary', 'Belarus', 'Media Manager III');
insert into workers (first_name, last_name, email, gender, country, job_title) values ('Bobbye', 'Jenne', 'bjenne61@hao123.com', 'Female', 'Indonesia', 'Financial Analyst');
insert into workers (first_name, last_name, email, gender, country, job_title) values ('Rosemary', 'Roadnight', 'rroadnight62@myspace.com', 'Female', 'Indonesia', 'Analog Circuit Design manager');
insert into workers (first_name, last_name, email, gender, country, job_title) values ('Batsheva', 'Colchett', 'bcolchett63@umn.edu', 'Female', 'Sri Lanka', 'Assistant Manager');
insert into workers (first_name, last_name, email, gender, country, job_title) values ('Ramon', 'Bezant', 'rbezant64@apache.org', 'Male', 'Philippines', 'Senior Developer');
insert into workers (first_name, last_name, email, gender, country, job_title) values ('Ryon', 'Whartonby', 'rwhartonby65@lycos.com', 'Male', 'Tunisia', 'Staff Accountant II');
insert into workers (first_name, last_name, email, gender, country, job_title) values ('Abba', 'Dunkerton', 'adunkerton66@state.gov', 'Male', 'Serbia', 'Office Assistant II');
insert into workers (first_name, last_name, email, gender, country, job_title) values ('Mufinella', 'Wass', 'mwass67@mit.edu', 'Female', 'France', 'Quality Engineer');
insert into workers (first_name, last_name, email, gender, country, job_title) values ('Kilian', 'Redparth', 'kredparth68@discuz.net', 'Male', 'Philippines', 'Automation Specialist III');
insert into workers (first_name, last_name, email, gender, country, job_title) values ('Zebulon', 'Reek', 'zreek69@home.pl', 'Male', 'Ukraine', 'Occupational Therapist');
insert into workers (first_name, last_name, email, gender, country, job_title) values ('Whit', 'Blacksland', 'wblacksland6a@nhs.uk', 'Male', 'Russia', 'Research Associate');
insert into workers (first_name, last_name, email, gender, country, job_title) values ('Alain', 'Bursnall', 'abursnall6b@technorati.com', 'Male', 'Argentina', 'Chemical Engineer');
insert into workers (first_name, last_name, email, gender, country, job_title) values ('Dolf', 'Finnick', 'dfinnick6c@amazon.de', 'Male', 'Portugal', 'GIS Technical Architect');
insert into workers (first_name, last_name, email, gender, country, job_title) values ('Ryun', 'Noor', 'rnoor6d@globo.com', 'Male', 'China', 'Recruiting Manager');
insert into workers (first_name, last_name, email, gender, country, job_title) values ('Mandel', 'McCord', 'mmccord6e@studiopress.com', 'Male', 'Sweden', 'Engineer III');
insert into workers (first_name, last_name, email, gender, country, job_title) values ('Vernice', 'Heintsch', 'vheintsch6f@umich.edu', 'Female', 'Iceland', 'Web Developer IV');
insert into workers (first_name, last_name, email, gender, country, job_title) values ('Katharina', 'Parminter', 'kparminter6g@plala.or.jp', 'Female', 'Uganda', 'Graphic Designer');
insert into workers (first_name, last_name, email, gender, country, job_title) values ('Gordie', 'Cashin', 'gcashin6h@whitehouse.gov', 'Male', 'Peru', 'Senior Cost Accountant');
insert into workers (first_name, last_name, email, gender, country, job_title) values ('Davin', 'Vedmore', 'dvedmore6i@economist.com', 'Male', 'Kosovo', 'Junior Executive');
insert into workers (first_name, last_name, email, gender, country, job_title) values ('Wally', 'Harlow', 'wharlow6j@census.gov', 'Male', 'Indonesia', 'Developer II');
insert into workers (first_name, last_name, email, gender, country, job_title) values ('Sybil', 'Abramski', 'sabramski6k@themeforest.net', 'Female', 'China', 'Administrative Assistant IV');
insert into workers (first_name, last_name, email, gender, country, job_title) values ('Monti', 'Dicty', 'mdicty6l@google.com.au', 'Male', 'Angola', 'Speech Pathologist');
insert into workers (first_name, last_name, email, gender, country, job_title) values ('Sergei', 'Kilmurry', 'skilmurry6m@google.co.uk', 'Male', 'Bosnia and Herzegovina', 'Senior Sales Associate');
insert into workers (first_name, last_name, email, gender, country, job_title) values ('Bambi', 'Edlyn', 'bedlyn6n@e-recht24.de', 'Female', 'Croatia', 'Electrical Engineer');
insert into workers (first_name, last_name, email, gender, country, job_title) values ('Arin', 'Sexcey', 'asexcey6o@cam.ac.uk', 'Male', 'China', 'GIS Technical Architect');
insert into workers (first_name, last_name, email, gender, country, job_title) values ('Susie', 'Bohling', 'sbohling6p@nature.com', 'Female', 'Poland', 'Systems Administrator III');
insert into workers (first_name, last_name, email, gender, country, job_title) values ('Abbey', 'Frankis', 'afrankis6q@toplist.cz', 'Male', 'Peru', 'Computer Systems Analyst IV');
insert into workers (first_name, last_name, email, gender, country, job_title) values ('Magnum', 'Lott', 'mlott6r@rambler.ru', 'Male', 'Indonesia', 'Health Coach II');
insert into workers (first_name, last_name, email, gender, country, job_title) values ('Tristan', 'Winsom', 'twinsom6s@mozilla.com', 'Genderfluid', 'Russia', 'Desktop Support Technician');
insert into workers (first_name, last_name, email, gender, country, job_title) values ('Shayla', 'Hulse', 'shulse6t@sitemeter.com', 'Female', 'China', 'Product Engineer');
insert into workers (first_name, last_name, email, gender, country, job_title) values ('Elmo', 'Glowacki', 'eglowacki6u@goo.gl', 'Male', 'Vietnam', 'Actuary');
insert into workers (first_name, last_name, email, gender, country, job_title) values ('Hugo', 'O''Canavan', 'hocanavan6v@cbslocal.com', 'Male', 'Peru', 'Design Engineer');
insert into workers (first_name, last_name, email, gender, country, job_title) values ('Franz', 'Bicknell', 'fbicknell6w@google.pl', 'Male', 'China', 'Cost Accountant');
insert into workers (first_name, last_name, email, gender, country, job_title) values ('Newton', 'Gianinotti', 'ngianinotti6x@jiathis.com', 'Male', 'Sweden', 'Marketing Assistant');
